### ISSUE TITLE
Readme app crashes

### ISSUE THREAD

**Issue by gaffo** [balzaczyy/golucene#4]
[TODO] ShallowSizeOfInstance(fst.Arc)
[TODO] ShallowSizeOfInstance(*fst.NoOutputs)
Found postings format: Lucene41
Found codec: Lucene42
Found codec: Lucene49
Found codec: Lucene410
2014/12/20 15:34:19 Setting default infoStream...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4df397]

goroutine 1 [running]:
github.com/balzaczyy/golucene/core/index.(*IndexWriter).AddDocument(0x0, 0xc20800b1f0, 0x1, 0x1, 0x0, 0x0)
	/home/mike/workspace-classyfier/src/github.com/balzaczyy/golucene/core/index/writer.go:562 +0x87
main.main()
	/home/mike/workspace-classyfier/src/github.com/gaffo/classyfier/main.go:182 +0x441

goroutine 5 [runnable]:
github.com/balzaczyy/golucene/core/index.(*ConcurrentMergeScheduler).worker(0xc2080464b0, 0x0)
	/home/mike/workspace-classyfier/src/github.com/balzaczyy/golucene/core/index/concurrentMergeScheduler.go:90
created by github.com/balzaczyy/golucene/core/index.(*ConcurrentMergeScheduler).SetMaxMergesAndRoutines
	/home/mike/workspace-classyfier/src/github.com/balzaczyy/golucene/core/index/concurrentMergeScheduler.go:148 +0x2b9

goroutine 6 [runnable]:
github.com/balzaczyy/golucene/core/index.(*ClosingControl).daemon(0xc20801e900)
	/home/mike/workspace-classyfier/src/github.com/balzaczyy/golucene/core/index/writer.go:101
created by github.com/balzaczyy/golucene/core/index.newClosingControl
	/home/mike/workspace-classyfier/src/github.com/balzaczyy/golucene/core/index/writer.go:97 +0xf1
exit status 2

**Comment by gaffo** [comment]
So I deleted that directory and a fresh pull of it seems to work fine. As does a run of all tests. So I'd call it fixed or no-issue. If I encounter it again I'll try for better error handling and get you a better bug report.
